const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const compiled = ts.transpileModule(fs.readFileSync('lib/native-transfer.ts', 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText;
const mod = { exports: {} };
new Function('exports', 'module', compiled)(mod.exports, mod);
const { NativeTransfer, NATIVE_MAX_BYTES } = mod.exports;
const begin = (size, name = 'wing.zip') => ({ type: 'aerovault:file-begin', requestId: 'request', name, size });
const chunk = (index, bytes) => ({ type: 'aerovault:file-chunk', requestId: 'request', index, data: Buffer.from(bytes).toString('base64') });
const finish = { type: 'aerovault:file-complete', requestId: 'request' };
function receiver(size = 3) { const t = new NativeTransfer('request'); t.consume(begin(size)); return t; }
(async () => {
    const transfer = receiver(5);
    assert.equal(transfer.consume({ ...chunk(0, [9]), requestId: 'stale' }), null);
    assert.equal(transfer.consume({ type: 'unrelated', requestId: 'request' }), null);
    assert.deepEqual(transfer.consume(chunk(0, [0, 255, 128])), { ack: 0 });
    assert.deepEqual(transfer.consume(chunk(1, [12, 42])), { ack: 1 });
    const { file } = transfer.consume(finish);
    assert.equal(file.name, 'wing.zip');
    assert.equal(file.type, 'application/zip');
    assert.deepEqual(new Uint8Array(await file.arrayBuffer()), new Uint8Array([0, 255, 128, 12, 42]));
    assert.throws(() => transfer.consume(finish), /already finished/);
    for (const size of [0, -1, 1.5, NaN, '3', NATIVE_MAX_BYTES + 1]) assert.throws(() => new NativeTransfer('request').consume(begin(size)));
    for (const name of ['../wing.zip', 'C:\\wing.zip', 'wing.exe', 'bad\n.zip']) assert.throws(() => new NativeTransfer('request').consume(begin(3, name)));
    assert.throws(() => receiver().consume(begin(3)), /invalid/);
    assert.throws(() => new NativeTransfer('request').consume(chunk(0, [1])), /interrupted/);
    assert.throws(() => receiver().consume(chunk(1, [1])), /interrupted/);
    assert.throws(() => receiver().consume(chunk(0, [1, 2, 3, 4])), /declared size/);
    assert.throws(() => receiver().consume(chunk(0, [])), /declared size/);
    assert.throws(() => receiver().consume(finish), /incomplete/);
    assert.throws(() => receiver().consume({ ...chunk(0, [1]), data: '*' }));
    assert.throws(() => receiver().consume({ ...chunk(0, [1]), data: 'A'.repeat(524289) }), /interrupted/);
    const duplicate = receiver(); duplicate.consume(chunk(0, [1]));
    assert.throws(() => duplicate.consume(chunk(0, [2])), /interrupted/);
    const large = receiver(384 * 1024 + 1);
    large.consume(chunk(0, Buffer.alloc(384 * 1024, 77)));
    large.consume(chunk(1, [99]));
    assert.equal(large.consume(finish).file.size, 384 * 1024 + 1);
    console.log('PASS: native transfer bytes, stale requests, declared limits, filenames, chunk ordering, duplicates, truncation, malformed base64, and full-sized chunks.');
})().catch(error => { console.error(error); process.exitCode = 1; });
